# **Kaggle – DataTops®**
Tu TA ha decidido cambiar de aires y, por eso, ha comprado una tienda de portátiles. Sin embargo, su única especialidad es Data Science, por lo que ha decidido crear un modelo de ML para establecer los mejores precios.

¿Podrías ayudar a tu profe a mejorar ese modelo?

## Aspectos importantes
- Última submission:
    - Mañana: 17 de febrero a las 5pm
    - Tarde: 19 de febrero a las 5pm
- **Enlace de la competición**: https://www.kaggle.com/t/c5cc87b50c4b4770bdc8f5acbe15577d
- **Requisito**: Estar registrado en [Kaggle](https://www.kaggle.com/)

## Métrica:
El error cuadrático medio (RMSE, por sus siglas en inglés) es una medida de la desviación estándar de los residuos (errores de predicción). Los residuos representan la diferencia entre los valores observados y los valores predichos por el modelo. El RMSE indica qué tan dispersos están estos errores: cuanto menor es el RMSE, más cercanas están las predicciones a los valores reales. En otras palabras, el RMSE mide qué tan bien se ajusta la línea de regresión a los datos.


$$ RMSE = \sqrt{\frac{1}{n}\Sigma_{i=1}^{n}{\Big(\frac{d_i -f_i}{\sigma_i}\Big)^2}}$$

## 1. Librerías

In [98]:
import numpy as np
import pandas as pd
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

import urllib.request
import matplotlib.pyplot as plt
import MyFunctions2 as mf    
import category_encoders as ce

## 2. Datos

In [99]:
# Para que funcione necesitas bajarte los archivos de datos de Kaggle
df = pd.read_csv("./data/train.csv")
X_pred = pd.read_csv("./data/test.csv")

### 2.1 Exploración de los datos

In [100]:
# Hacemos que nuestro índice sea el id
df.set_index("laptop_ID", inplace=True)
X_pred.set_index("laptop_ID", inplace=True)

y_test_pred = pd.read_csv("./data/test2.csv", sep=';')
y_test_pred.set_index("laptop_ID", inplace=True)

In [101]:
df["Price_in_euros"] = np.log1p(df["Price_in_euros"])
#y_test_pred["Price_in_euros"] = np.log1p(y_test_pred["Price_in_euros"])

### 2.3 Dividir X_train, X_test, y_train, y_test

In [102]:
train_set, test_set = train_test_split(df, test_size = 0.2, random_state = 42)

In [103]:
target_col = "Price_in_euros"
features = [c for c in train_set.columns if c != target_col]

y_train = train_set[target_col]
y_test = test_set[target_col]

X_train = train_set[features]
X_test = test_set[features]

In [104]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 729 entries, 1118 to 418
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           729 non-null    object
 1   Product           729 non-null    object
 2   TypeName          729 non-null    object
 3   Inches            729 non-null    float64
 4   ScreenResolution  729 non-null    object
 5   Cpu               729 non-null    object
 6   Ram               729 non-null    object
 7   Memory            729 non-null    object
 8   Gpu               729 non-null    object
 9   OpSys             729 non-null    object
 10  Weight            729 non-null    object
dtypes: float64(1), object(10)
memory usage: 68.3+ KB

In [105]:
def transformar_datos(df):

    mf.screen_resolution_split(df)
    mf.replace_value(df, "Ram", "GB", "", int)

    mf.replace_value(df, "Weight", "kg", "", float)
    mf.memory_split(df)

    mf.procesar_cpu_caotico(df, "Cpu")

    # df['Cpu_Tier'] = df['cpu_familia'].apply(mf.categorizar_procesador)
    # df.drop(["cpu_familia"], axis=1, inplace=True)
    
    mf.gpu_split3(df)
    df.drop(["Product"], axis=1, inplace=True)

    # df['Performance_Weight_Ratio'] = df['cpu_ghz'] / df['Weight_kg']
    # df['Cpu_Performance_Index'] = df['Cpu_Tier'] * df['cpu_ghz']
    # df['Ram_GHz_Ratio'] = df['Ram_GB'] / df['cpu_ghz']
    # df['Power_Density'] = (df['Ram_GB'] * df['cpu_ghz']) / df['Weight_kg']

    # df.drop(["cpu_ghz"], axis=1, inplace=True)
    # df.drop(["Weight_kg"], axis=1, inplace=True)

    

    return df

In [108]:
from lightgbm import LGBMRegressor
from sklearn.calibration import LabelEncoder
from sklearn.metrics import mean_squared_error


def transformar_datos2(df):

    df["Touchscreen"] = df["ScreenResolution"].str.contains("Touchscreen").astype(int)
    df["IPS"] = df["ScreenResolution"].str.contains("IPS").astype(int)

    res = df["ScreenResolution"].str.extract(r'(\d+)x(\d+)')
    df["ResX"] = res[0].astype(float)
    df["ResY"] = res[1].astype(float)

    df["PPI"] = ((df["ResX"]**2 + df["ResY"]**2)**0.5) / df["Inches"]

    df["Cpu_brand"] = df["Cpu"].str.split().str[0]
    df["Cpu_family"] = df["Cpu"].str.extract(r'(i3|i5|i7|i9|Ryzen|Pentium|Celeron|Atom)')
    df["Cpu_speed"] = df["Cpu"].str.extract(r'(\d\.\d+)GHz').astype(float)

    df["Gpu_brand"] = df["Gpu"].str.split().str[0]
    df["Gpu_dedicated"] = df["Gpu_brand"].apply(lambda x: 0 if x=="Intel" else 1)

    def parse_memory(mem):
        mem = mem.replace("GB", "").replace("TB", "000")
        parts = mem.split("+")
        hdd = ssd = flash = hybrid = 0
        for p in parts:
            p = p.strip()
            if "HDD" in p:
                hdd += float(p.split()[0])
            elif "SSD" in p:
                ssd += float(p.split()[0])
            elif "Flash" in p:
                flash += float(p.split()[0])
            elif "Hybrid" in p:
                hybrid += float(p.split()[0])
        return pd.Series([hdd, ssd, flash, hybrid])

    df[["HDD", "SSD", "Flash", "Hybrid"]] = df["Memory"].apply(parse_memory)
    df["Total_Storage"] = df[["HDD","SSD","Flash","Hybrid"]].sum(axis=1)
  
    mf.replace_value(df, "Ram", "GB", "", int)

    mf.replace_value(df, "Weight", "kg", "", float)

    df["Cpu_gen"] = df["Cpu"].str.extract(r'(\d{4})') 
    df["Cpu_gen"] = df["Cpu_gen"].astype(float) // 100 
    df["Cpu_gen"] = df["Cpu_gen"].fillna(df["Cpu_gen"].median())

    df["Gpu_model_num"] = df["Gpu"].str.extract(r'(\d{3,4})').astype(float) 
    df["Gpu_model_num"] = df["Gpu_model_num"].fillna(0)
    df["Gpu_is_integrated"] = (df["Gpu_brand"] == "Intel").astype(int)
    df["Cpu_power"] = df["Cpu_gen"] * df["Cpu_speed"]
    df["Gpu_power"] = df["Gpu_dedicated"] * df["Gpu_model_num"]

    df["Has_SSD"] = (df["SSD"] > 0).astype(int) 
    df["Has_HDD"] = (df["HDD"] > 0).astype(int)
    df["Storage_speed"] = df["Has_SSD"] * 2 + df["Has_HDD"] * 1

    df["Weight_per_inch"] = df["Weight_kg"] / df["Inches"]
    df["Ram_per_kg"] = df["Ram_GB"] / df["Weight_kg"]

    def resolution_category(x): 
        if "3840" in x: return "4K" 
        if "3200" in x or "2560" in x: return "2K" 
        if "1920" in x: return "FHD" 
        return "HD" 
    
    #df["ResCategory"] = df["ScreenResolution"].apply(resolution_category)
    df["Weight_norm"] = df["Weight_kg"] / df["Weight_kg"].max() 
    df["Ram_norm"] = df["Ram_GB"] / 32

    df.drop(["Product","ScreenResolution", "Cpu", "Gpu", "Memory"], axis=1, inplace=True)

    return df

In [109]:
from sklearn.preprocessing import RobustScaler

X_train = transformar_datos2(X_train)
X_test = transformar_datos2(X_test)
X_pred = transformar_datos2(X_pred)

X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 729 entries, 1118 to 418
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            729 non-null    object
 1   TypeName           729 non-null    object
 2   Inches             729 non-null    float64
 3   OpSys              729 non-null    object
 4   Touchscreen        729 non-null    int64
 5   IPS                729 non-null    int64
 6   ResX               729 non-null    float64
 7   ResY               729 non-null    float64
 8   PPI                729 non-null    float64
 9   Cpu_brand          729 non-null    object
 10  Cpu_family         688 non-null    object
 11  Cpu_speed          686 non-null    float64
 12  Gpu_brand          729 non-null    object
 13  Gpu_dedicated      729 non-null    int64
 14  HDD                729 non-null    float64
 15  SSD                729 non-null    float64
 16  Flash              729 non-null    float64
 17  Hybrid             729 non-null    float64
 18  Total_Storage      729 non-null    float64
 19  Ram_GB             729 non-null    int64
 20  Weight_kg          729 non-null    float64
 21  Cpu_gen            729 non-null    float64
 22  Gpu_model_num      729 non-null    float64
 23  Gpu_is_integrated  729 non-null    int64
 24  Cpu_power          686 non-null    float64
 25  Gpu_power          729 non-null    float64
 26  Has_SSD            729 non-null    int64
 27  Has_HDD            729 non-null    int64
 28  Storage_speed      729 non-null    int64
 29  Weight_per_inch    729 non-null    float64
 30  Ram_per_kg         729 non-null    float64
 31  Weight_norm        729 non-null    float64
 32  Ram_norm           729 non-null    float64
dtypes: float64(19), int64(8), object(6)
memory usage: 193.6+ KB

In [110]:
X_train.head()

,Company,TypeName,Inches,OpSys,Touchscreen,IPS,ResX,ResY,PPI,Cpu_brand,...,Gpu_is_integrated,Cpu_power,Gpu_power,Has_SSD,Has_HDD,Storage_speed,Weight_per_inch,Ram_per_kg,Weight_norm,Ram_norm
laptop_ID,,,,,,,,,,,,,,,,,,,,,
1118,HP,Workstation,17.3,Windows 7,0,1,1920.0,1080.0,127.335675,Intel,...,0,174.2,6150.0,0,1,1,0.173410,2.666667,0.638298,0.250
153,Dell,Gaming,15.6,Windows 10,0,0,1920.0,1080.0,141.211998,Intel,...,0,215.6,1050.0,1,0,2,0.164103,6.250000,0.544681,0.500
275,Apple,Ultrabook,13.3,macOS,0,1,2560.0,1600.0,226.983005,Intel,...,1,208.8,0.0,1,0,2,0.103008,5.839416,0.291489,0.250
1100,HP,Notebook,14.0,Windows 7,0,0,1920.0,1080.0,157.350512,Intel,...,1,142.6,0.0,0,1,1,0.110000,2.597403,0.327660,0.125
131,Dell,Notebook,17.3,Windows 10,0,0,1920.0,1080.0,127.335675,Intel,...,0,153.0,530.0,1,1,3,0.161850,5.714286,0.595745,0.500

In [111]:
# cat_cols = X_train.select_dtypes(include='object').columns.tolist()

cat_cols = ["Company","TypeName","OpSys","Cpu_brand","Cpu_family","Gpu_brand"]
encoder = ce.TargetEncoder(cols=cat_cols)
X_train[cat_cols] = encoder.fit_transform(X_train[cat_cols], y_train)
X_test[cat_cols] = encoder.transform(X_test[cat_cols])
X_pred[cat_cols] = encoder.transform(X_pred[cat_cols])

In [112]:
for col in X_train.select_dtypes(include='object').columns:
    print(f"{col}: {X_train[col].nunique()} categorías")

In [113]:
# Eliminar variables con baja correlación respecto al target
# Solo considerar columnas numéricas para la correlación
def drop_low_correlation_features(X, y, threshold=0.05):
    X_numeric = X.select_dtypes(include=[np.number])
    corrs = X_numeric.corrwith(y).abs()
    low_corr_cols = corrs[corrs < threshold].index.tolist()
    print(f"Eliminando {len(low_corr_cols)} columnas con correlación < {threshold}: {low_corr_cols}")
    return X.drop(columns=low_corr_cols), low_corr_cols

X_train, dropped_low_corr = drop_low_correlation_features(X_train, y_train, threshold=0.05)
X_test = X_test.drop(columns=dropped_low_corr)
X_pred = X_pred.drop(columns=dropped_low_corr)

Eliminando 3 columnas con correlación < 0.05: ['Inches', 'Flash', 'Hybrid']

In [114]:
# Calcular la correlación de cada feature con el target
correlation = X_train.corrwith(y_train)
correlation.sort_values(ascending=False, inplace=True)
correlation

Cpu_family           0.768871
Ram_GB               0.677051
Ram_norm             0.677051
TypeName             0.641322
SSD                  0.633920
Ram_per_kg           0.629793
Storage_speed        0.605618
Has_SSD              0.592999
ResY                 0.559496
ResX                 0.557786
Cpu_power            0.539200
Cpu_speed            0.500856
PPI                  0.490018
Cpu_gen              0.452715
Gpu_brand            0.355235
OpSys                0.349454
Company              0.346207
Gpu_power            0.330327
IPS                  0.292776
Gpu_model_num        0.284557
Touchscreen          0.234763
Cpu_brand            0.223724
Gpu_dedicated        0.195111
Total_Storage        0.181288
Weight_norm          0.140551
Weight_kg            0.140551
Weight_per_inch      0.132693
HDD                 -0.063261
Has_HDD             -0.160063
Gpu_is_integrated   -0.195111
dtype: float64

In [115]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

# Entrenar el modelo Random Forest
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

def predecir(model, X_test, y_test):
    # Predecir sobre el test
    y_pred = model.predict(X_test)

    y_pred = np.expm1(y_pred)
    # Calcular RMSE en escala logarítmica
    rmse_log = np.sqrt(mean_squared_error(y_test, y_pred))
    print(f"RMSE (log1p): {rmse_log:.4f}")

    print(np.sqrt(mean_squared_error(y_test, y_pred))) 
    print(np.sqrt(mean_squared_error(y_test, np.mean(y_test)*np.ones_like(y_test))))

    # # Calcular RMSE en escala original (deshacer log1p)
    # y_test_exp = np.expm1(y_test)
    # y_pred_exp = np.expm1(y_pred)
    # rmse_original = np.sqrt(mean_squared_error(y_test_exp, y_pred_exp))
    # print(f"RMSE (escala original): {rmse_original:.2f}")

In [116]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
import numpy as np

# Búsqueda de hiperparámetros ampliada para RandomForest
param_grid = {
    'n_estimators': [100, 200, 400],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 4, 8],
    'max_features': ['sqrt', 'log2', None],
    'bootstrap': [True, False],
    'random_state': [42]

}

rf = RandomForestRegressor(random_state=42)
grid_search_rf = GridSearchCV(
    rf, param_grid, cv=3, scoring='neg_root_mean_squared_error', n_jobs=-1, verbose=2
)
grid_search_rf.fit(X_train, y_train)

Fitting 3 folds for each of 1152 candidates, totalling 3456 fits

GridSearchCV(cv=3, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'max_depth': [None, 10, 20, 30],
                         'max_features': ['sqrt', 'log2', None],
                         'min_samples_leaf': [1, 2, 4, 8],
                         'min_samples_split': [2, 5, 10, 20],
                         'n_estimators': [100, 200, 400],
                         'random_state': [42]},
             scoring='neg_root_mean_squared_error', verbose=2)

In [117]:
import optuna
import xgboost as xgb
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error

# Optuna para XGBoost

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 600),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 10),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 10),
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 10),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'random_state': 42
    }
    model = xgb.XGBRegressor(**params)
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error').mean()
    return score

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=75)

print("Mejores hiperparámetros XGBoost:", study.best_params)

# Entrenar modelo final con los mejores hiperparámetros
best_params = study.best_params
model_xgb_optuna = xgb.XGBRegressor(**best_params)
model_xgb_optuna.fit(X_train, y_train)

[I 2026-02-16 23:53:09,429] A new study created in memory with name: no-name-1466e7d3-132d-4ec9-a9ce-714e5ab95c25
[I 2026-02-16 23:53:09,648] Trial 0 finished with value: -0.2643433634321725 and parameters: {'max_depth': 7, 'learning_rate': 0.24517932047070642, 'n_estimators': 466, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'gamma': 1.5599452033620265, 'reg_alpha': 0.5808361216819946, 'reg_lambda': 8.661761457749352, 'min_child_weight': 7}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:10,029] Trial 1 finished with value: -0.28297259501253563 and parameters: {'max_depth': 12, 'learning_rate': 0.005439667429522981, 'n_estimators': 585, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.6061695553391381, 'gamma': 1.8182496720710062, 'reg_alpha': 1.8340450985343382, 'reg_lambda': 3.0424224295953772, 'min_child_weight': 6}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:10,250] Trial 2 finished with value: -0.33714206260099683 and parameters: {'max_depth': 8, 'learning_rate': 0.01647477394109053, 'n_estimators': 406, 'subsample': 0.569746930326021, 'colsample_bytree': 0.6460723242676091, 'gamma': 3.663618432936917, 'reg_alpha': 4.56069984217036, 'reg_lambda': 7.851759613930136, 'min_child_weight': 2}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:10,361] Trial 3 finished with value: -0.3019611858054751 and parameters: {'max_depth': 9, 'learning_rate': 0.056542201075504325, 'n_estimators': 123, 'subsample': 0.8037724259507192, 'colsample_bytree': 0.5852620618436457, 'gamma': 0.6505159298527952, 'reg_alpha': 9.488855372533333, 'reg_lambda': 9.656320330745594, 'min_child_weight': 9}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:10,630] Trial 4 finished with value: -0.321756891685534 and parameters: {'max_depth': 6, 'learning_rate': 0.007458402142772737, 'n_estimators': 442, 'subsample': 0.7200762468698007, 'colsample_bytree': 0.5610191174223894, 'gamma': 4.951769101112702, 'reg_alpha': 0.34388521115218396, 'reg_lambda': 9.093204020787821, 'min_child_weight': 3}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:10,852] Trial 5 finished with value: -0.39327070765320205 and parameters: {'max_depth': 11, 'learning_rate': 0.017915933593754683, 'n_estimators': 360, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'gamma': 9.695846277645586, 'reg_alpha': 7.7513282336111455, 'reg_lambda': 9.394989415641891, 'min_child_weight': 9}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:10,941] Trial 6 finished with value: -0.31436375578290093 and parameters: {'max_depth': 10, 'learning_rate': 0.21787220464104293, 'n_estimators': 144, 'subsample': 0.5979914312095727, 'colsample_bytree': 0.522613644455269, 'gamma': 3.2533033076326436, 'reg_alpha': 3.8867728968948203, 'reg_lambda': 2.713490317738959, 'min_child_weight': 9}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:11,170] Trial 7 finished with value: -0.32348626039539213 and parameters: {'max_depth': 7, 'learning_rate': 0.015794797197594638, 'n_estimators': 371, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'gamma': 0.7455064367977082, 'reg_alpha': 9.868869366005173, 'reg_lambda': 7.722447692966574, 'min_child_weight': 2}. Best is trial 0 with value: -0.2643433634321725.
[I 2026-02-16 23:53:11,385] Trial 8 finished with value: -0.2632198163972794 and parameters: {'max_depth': 3, 'learning_rate': 0.1409236110165583, 'n_estimators': 454, 'subsample': 0.8645035840204937, 'colsample_bytree': 0.8856351733429728, 'gamma': 0.7404465173409036, 'reg_alpha': 3.5846572854427263, 'reg_lambda': 1.1586905952512971, 'min_child_weight': 9}. Best is trial 8 with value: -0.2632198163972794.
[I 2026-02-16 23:53:11,488] Trial 9 finished with value: -0.3844242784893978 and parameters: {'max_depth': 11, 'learning_rate': 0.0193801324564921, 'n_estimators': 131, 'subsample': 0.6554911608578311, 'colsample_bytree': 0.6625916610133735, 'gamma': 7.29606178338064, 'reg_alpha': 6.3755747135521315, 'reg_lambda': 8.872127425763265, 'min_child_weight': 5}. Best is trial 8 with value: -0.2632198163972794.
[I 2026-02-16 23:53:11,644] Trial 10 finished with value: -0.3303977092020871 and parameters: {'max_depth': 3, 'learning_rate': 0.09007047239365772, 'n_estimators': 254, 'subsample': 0.968324376628699, 'colsample_bytree': 0.9896117410993797, 'gamma': 6.902470735691452, 'reg_alpha': 2.579269526014921, 'reg_lambda': 0.11114384822711276, 'min_child_weight': 10}. Best is trial 8 with value: -0.2632198163972794.
[I 2026-02-16 23:53:11,883] Trial 11 finished with value: -0.2713956483279388 and parameters: {'max_depth': 15, 'learning_rate': 0.28976220200622305, 'n_estimators': 535, 'subsample': 0.84937152114332, 'colsample_bytree': 0.7848596544349612, 'gamma': 2.362640564998433, 'reg_alpha': 0.4121117384896067, 'reg_lambda': 5.732909776512291, 'min_child_weight': 7}. Best is trial 8 with value: -0.2632198163972794.
[I 2026-02-16 23:53:12,119] Trial 12 finished with value: -0.25199420775059694 and parameters: {'max_depth': 3, 'learning_rate': 0.13248542663134377, 'n_estimators': 495, 'subsample': 0.8605213354247511, 'colsample_bytree': 0.8045369317168722, 'gamma': 0.4724097526238986, 'reg_alpha': 2.90913655267625, 'reg_lambda': 0.33585884934472254, 'min_child_weight': 7}. Best is trial 12 with value: -0.25199420775059694.
[I 2026-02-16 23:53:12,359] Trial 13 finished with value: -0.24736219835246365 and parameters: {'max_depth': 3, 'learning_rate': 0.10286991191944622, 'n_estimators': 499, 'subsample': 0.893515125575913, 'colsample_bytree': 0.8079213947096819, 'gamma': 0.2554949481054347, 'reg_alpha': 3.012897435936558, 'reg_lambda': 0.4875480009875891, 'min_child_weight': 7}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:12,638] Trial 14 finished with value: -0.2656459308217705 and parameters: {'max_depth': 5, 'learning_rate': 0.07774706392139472, 'n_estimators': 527, 'subsample': 0.9980084946806067, 'colsample_bytree': 0.761655546480765, 'gamma': 0.21271302968900574, 'reg_alpha': 5.775718258393615, 'reg_lambda': 2.1517803616931235, 'min_child_weight': 5}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:12,795] Trial 15 finished with value: -0.3094037750070614 and parameters: {'max_depth': 4, 'learning_rate': 0.1252314295251389, 'n_estimators': 275, 'subsample': 0.9094719080896364, 'colsample_bytree': 0.8288353090998428, 'gamma': 4.13440520410747, 'reg_alpha': 2.160139447756661, 'reg_lambda': 4.633767513875689, 'min_child_weight': 7}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:13,080] Trial 16 finished with value: -0.3303105934560198 and parameters: {'max_depth': 5, 'learning_rate': 0.03889586008202006, 'n_estimators': 592, 'subsample': 0.7177343251658946, 'colsample_bytree': 0.7057842336829495, 'gamma': 5.769491738896778, 'reg_alpha': 3.097007797167165, 'reg_lambda': 0.27219026391196977, 'min_child_weight': 4}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:13,324] Trial 17 finished with value: -0.3106454636253393 and parameters: {'max_depth': 3, 'learning_rate': 0.14444331756035042, 'n_estimators': 508, 'subsample': 0.9257586930950283, 'colsample_bytree': 0.8448372126058836, 'gamma': 2.8471055852412386, 'reg_alpha': 5.06776256871667, 'reg_lambda': 4.18200137581984, 'min_child_weight': 6}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:13,483] Trial 18 finished with value: -0.3714421756964603 and parameters: {'max_depth': 5, 'learning_rate': 0.043360167182103046, 'n_estimators': 288, 'subsample': 0.5100896972990723, 'colsample_bytree': 0.9482719526762666, 'gamma': 9.309781571936997, 'reg_alpha': 1.728561667390637, 'reg_lambda': 1.3629325317271208, 'min_child_weight': 8}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:13,748] Trial 19 finished with value: -0.30650845446111663 and parameters: {'max_depth': 14, 'learning_rate': 0.0797292044997927, 'n_estimators': 492, 'subsample': 0.8680971393569991, 'colsample_bytree': 0.7321657739859632, 'gamma': 1.5232226169728342, 'reg_alpha': 7.4633083129078575, 'reg_lambda': 5.894749398228652, 'min_child_weight': 4}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:13,956] Trial 20 finished with value: -0.32522718208986073 and parameters: {'max_depth': 4, 'learning_rate': 0.02874130035116126, 'n_estimators': 401, 'subsample': 0.8367608379983338, 'colsample_bytree': 0.8153735231476509, 'gamma': 4.452870098751182, 'reg_alpha': 4.333579331824903, 'reg_lambda': 3.624938995780427, 'min_child_weight': 8}. Best is trial 13 with value: -0.24736219835246365.
[I 2026-02-16 23:53:14,167] Trial 21 finished with value: -0.24301225349186575 and parameters: {'max_depth': 3, 'learning_rate': 0.1500629562632332, 'n_estimators': 448, 'subsample': 0.8758275837807667, 'colsample_bytree': 0.8980540623390069, 'gamma': 0.1260742839224933, 'reg_alpha': 3.340098499590434, 'reg_lambda': 1.056710410597408, 'min_child_weight': 10}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:14,416] Trial 22 finished with value: -0.2498574302763871 and parameters: {'max_depth': 4, 'learning_rate': 0.15968510951335363, 'n_estimators': 546, 'subsample': 0.8977056730193086, 'colsample_bytree': 0.8842478833829477, 'gamma': 0.3312137861963402, 'reg_alpha': 3.140321182599708, 'reg_lambda': 1.114735679427293, 'min_child_weight': 10}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:14,668] Trial 23 finished with value: -0.2767954038280818 and parameters: {'max_depth': 6, 'learning_rate': 0.1908692046889518, 'n_estimators': 553, 'subsample': 0.9519167591647085, 'colsample_bytree': 0.8833953485805045, 'gamma': 1.8992942385884937, 'reg_alpha': 1.5171602861436977, 'reg_lambda': 1.5684117707469443, 'min_child_weight': 10}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:14,882] Trial 24 finished with value: -0.25348463086347567 and parameters: {'max_depth': 4, 'learning_rate': 0.0979604252526861, 'n_estimators': 419, 'subsample': 0.8903337975152915, 'colsample_bytree': 0.9439446793075706, 'gamma': 0.09898011718284724, 'reg_alpha': 5.1079085228850865, 'reg_lambda': 2.0896606430953737, 'min_child_weight': 10}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:15,058] Trial 25 finished with value: -0.28259711746955646 and parameters: {'max_depth': 6, 'learning_rate': 0.17730843568817226, 'n_estimators': 317, 'subsample': 0.9565438260516148, 'colsample_bytree': 0.8595948953334945, 'gamma': 1.2860255427413194, 'reg_alpha': 3.586587051945685, 'reg_lambda': 0.987493478528779, 'min_child_weight': 8}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:15,325] Trial 26 finished with value: -0.2814715630543087 and parameters: {'max_depth': 4, 'learning_rate': 0.058758662051987355, 'n_estimators': 561, 'subsample': 0.8136917976630381, 'colsample_bytree': 0.930735940134022, 'gamma': 2.5218008402505134, 'reg_alpha': 1.0943384555733957, 'reg_lambda': 2.431360648805974, 'min_child_weight': 10}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:15,572] Trial 27 finished with value: -0.26682521962120576 and parameters: {'max_depth': 5, 'learning_rate': 0.1049806126964528, 'n_estimators': 476, 'subsample': 0.7500949942496842, 'colsample_bytree': 0.9706618406864866, 'gamma': 1.12404092383743, 'reg_alpha': 2.5319830731682753, 'reg_lambda': 3.386171833522072, 'min_child_weight': 8}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:15,759] Trial 28 finished with value: -0.2566263516777227 and parameters: {'max_depth': 7, 'learning_rate': 0.06394226826956279, 'n_estimators': 211, 'subsample': 0.9023744245053996, 'colsample_bytree': 0.9158840279963768, 'gamma': 0.0821515158684892, 'reg_alpha': 6.014501645021321, 'reg_lambda': 0.759704586065372, 'min_child_weight': 1}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:15,986] Trial 29 finished with value: -0.2882598082203189 and parameters: {'max_depth': 8, 'learning_rate': 0.2814376200212953, 'n_estimators': 468, 'subsample': 0.9911553046230503, 'colsample_bytree': 0.8677167844819031, 'gamma': 1.928423486452738, 'reg_alpha': 3.318404746538009, 'reg_lambda': 1.8733646259217658, 'min_child_weight': 9}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:16,250] Trial 30 finished with value: -0.3110136528757614 and parameters: {'max_depth': 3, 'learning_rate': 0.18812955765051803, 'n_estimators': 435, 'subsample': 0.8244811489476257, 'colsample_bytree': 0.7814834816112007, 'gamma': 5.906684303812539, 'reg_alpha': 0.9173109600314624, 'reg_lambda': 0.8211060962495205, 'min_child_weight': 6}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:16,545] Trial 31 finished with value: -0.26262333772828655 and parameters: {'max_depth': 3, 'learning_rate': 0.13643084868853184, 'n_estimators': 509, 'subsample': 0.873467500246944, 'colsample_bytree': 0.8093120787751478, 'gamma': 0.8268677266567377, 'reg_alpha': 2.7109126431182626, 'reg_lambda': 0.003407581441091878, 'min_child_weight': 7}. Best is trial 21 with value: -0.24301225349186575.
[I 2026-02-16 23:53:16,904] Trial 32 finished with value: -0.2406969610408681 and parameters: {'max_depth': 4, 'learning_rate': 0.11399776747759868, 'n_estimators': 566, 'subsample': 0.7919855147666942, 'colsample_bytree': 0.7329914686789151, 'gamma': 0.04735194953061561, 'reg_alpha': 4.146444635023145, 'reg_lambda': 0.5887703617906848, 'min_child_weight': 7}. Best is trial 32 with value: -0.2406969610408681.
[I 2026-02-16 23:53:17,443] Trial 33 finished with value: -0.287453308580268 and parameters: {'max_depth': 4, 'learning_rate': 0.2349954267287274, 'n_estimators': 596, 'subsample': 0.7661599768287951, 'colsample_bytree': 0.7108205000426832, 'gamma': 1.4274312654048429, 'reg_alpha': 4.153763299732572, 'reg_lambda': 1.544926393736054, 'min_child_weight': 6}. Best is trial 32 with value: -0.2406969610408681.
[I 2026-02-16 23:53:17,739] Trial 34 finished with value: -0.2966095940558945 and parameters: {'max_depth': 5, 'learning_rate': 0.11263703310670597, 'n_estimators': 556, 'subsample': 0.786371656057562, 'colsample_bytree': 0.6640253143746593, 'gamma': 2.0046799206977313, 'reg_alpha': 4.826370427169619, 'reg_lambda': 0.7106005348870729, 'min_child_weight': 8}. Best is trial 32 with value: -0.2406969610408681.
[I 2026-02-16 23:53:18,035] Trial 35 finished with value: -0.23739278174292086 and parameters: {'max_depth': 6, 'learning_rate': 0.17431261946420676, 'n_estimators': 576, 'subsample': 0.931507762058805, 'colsample_bytree': 0.8479434027188816, 'gamma': 0.10754325206586857, 'reg_alpha': 2.1275181468438378, 'reg_lambda': 3.105149764572572, 'min_child_weight': 10}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:18,318] Trial 36 finished with value: -0.2694771132478933 and parameters: {'max_depth': 6, 'learning_rate': 0.046572042863256696, 'n_estimators': 565, 'subsample': 0.9250085955171129, 'colsample_bytree': 0.7398432662650346, 'gamma': 1.2848479025506503, 'reg_alpha': 2.087760424972847, 'reg_lambda': 3.1588034345312583, 'min_child_weight': 9}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:18,560] Trial 37 finished with value: -0.2780034436629157 and parameters: {'max_depth': 8, 'learning_rate': 0.07500145931499089, 'n_estimators': 520, 'subsample': 0.7125582808434879, 'colsample_bytree': 0.625796303597987, 'gamma': 2.798163661523291, 'reg_alpha': 0.04069232418913238, 'reg_lambda': 2.6649654449640567, 'min_child_weight': 4}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:18,829] Trial 38 finished with value: -0.2759336594215576 and parameters: {'max_depth': 9, 'learning_rate': 0.21089160506570165, 'n_estimators': 599, 'subsample': 0.9385297574842197, 'colsample_bytree': 0.6948989576956766, 'gamma': 0.9000334884073135, 'reg_alpha': 3.988055252626073, 'reg_lambda': 3.790875271786244, 'min_child_weight': 7}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:19,067] Trial 39 finished with value: -0.3004132968830813 and parameters: {'max_depth': 7, 'learning_rate': 0.031964196571296, 'n_estimators': 397, 'subsample': 0.801872618278901, 'colsample_bytree': 0.7683151304313172, 'gamma': 3.432465300458068, 'reg_alpha': 1.2690106660849048, 'reg_lambda': 5.435447774033777, 'min_child_weight': 5}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:19,448] Trial 40 finished with value: -0.2718408725303685 and parameters: {'max_depth': 6, 'learning_rate': 0.01065977486348013, 'n_estimators': 477, 'subsample': 0.6658846912165496, 'colsample_bytree': 0.8455726377198928, 'gamma': 0.10250219375569014, 'reg_alpha': 5.473142854921256, 'reg_lambda': 6.751376841209982, 'min_child_weight': 9}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:19,716] Trial 41 finished with value: -0.25709969461290344 and parameters: {'max_depth': 4, 'learning_rate': 0.16889402377568258, 'n_estimators': 551, 'subsample': 0.8918903809272263, 'colsample_bytree': 0.8953772911688846, 'gamma': 0.5509551490204299, 'reg_alpha': 3.4605847544328165, 'reg_lambda': 1.694845135394611, 'min_child_weight': 10}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:20,037] Trial 42 finished with value: -0.24316771121757666 and parameters: {'max_depth': 4, 'learning_rate': 0.15265348269521758, 'n_estimators': 573, 'subsample': 0.887440382080383, 'colsample_bytree': 0.8318458717268541, 'gamma': 0.03780369062892097, 'reg_alpha': 4.530925003340923, 'reg_lambda': 0.6547035287542853, 'min_child_weight': 10}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:20,320] Trial 43 finished with value: -0.2755842109316569 and parameters: {'max_depth': 3, 'learning_rate': 0.24788127502971866, 'n_estimators': 579, 'subsample': 0.9787516852014605, 'colsample_bytree': 0.7916690640814229, 'gamma': 0.8750064086504009, 'reg_alpha': 4.477874681776259, 'reg_lambda': 0.6328291260429993, 'min_child_weight': 9}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:20,665] Trial 44 finished with value: -0.25588521908368805 and parameters: {'max_depth': 5, 'learning_rate': 0.11059211241004537, 'n_estimators': 529, 'subsample': 0.8442860561847538, 'colsample_bytree': 0.8380655654121906, 'gamma': 0.6260165774781203, 'reg_alpha': 2.24868786840603, 'reg_lambda': 2.949856772543419, 'min_child_weight': 9}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:20,950] Trial 45 finished with value: -0.2887502436992625 and parameters: {'max_depth': 3, 'learning_rate': 0.0946865843123417, 'n_estimators': 451, 'subsample': 0.9487565317248786, 'colsample_bytree': 0.8637824224165317, 'gamma': 1.5706109053230293, 'reg_alpha': 3.8303216540775336, 'reg_lambda': 2.2971838136872447, 'min_child_weight': 10}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:21,310] Trial 46 finished with value: -0.34952580596126553 and parameters: {'max_depth': 4, 'learning_rate': 0.14975325369027828, 'n_estimators': 577, 'subsample': 0.8716671434851786, 'colsample_bytree': 0.7541192038556279, 'gamma': 8.609030771728927, 'reg_alpha': 4.6676702498920655, 'reg_lambda': 0.4212814506727174, 'min_child_weight': 8}. Best is trial 35 with value: -0.23739278174292086.
[I 2026-02-16 23:53:21,674] Trial 47 finished with value: -0.25866323105303674 and parameters: {'max_depth': 13, 'learning_rate': 0.0673554638500319, 'n_estimators': 495, 'subsample': 0.9315263940828625, 'colsample_bytree': 0.5538332346301195, 'gamma': 0.037025300664513254, 'reg_alpha': 7.2164330118777515, 'reg_lambda': 0.025480279048816334, 'min_child_weight': 9}. Best is trial 35 with value: -0.23739278174292086.

Mejores hiperparámetros XGBoost: {'max_depth': 9, 'learning_rate': 0.20487125223768562, 'n_estimators': 191, 'subsample': 0.8767299351668862, 'colsample_bytree': 0.9996503871976347, 'gamma': 0.0015156320097993586, 'reg_alpha': 0.6989984087130298, 'reg_lambda': 6.526380416402371, 'min_child_weight': 10}

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9996503871976347, device=None,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=0.0015156320097993586, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.20487125223768562, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=9, max_leaves=None,
             min_child_weight=10, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=191, n_jobs=None,
             num_parallel_tree=None, ...)

In [118]:
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error

def objective_lgb(trial):
    params = {
        'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'n_estimators': trial.suggest_int('n_estimators', 100, 300),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 30),
        'subsample': trial.suggest_float('subsample', 0.7, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 5),
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 5),
        'random_state': 42,
        'verbose': -1
    }
    model = lgb.LGBMRegressor(**params)
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error').mean()
    return score

study_lgb = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study_lgb.optimize(objective_lgb, n_trials=50)

print("Mejores hiperparámetros LightGBM:", study_lgb.best_params)

best_params_lgb = study_lgb.best_params
model_lgb_optuna = lgb.LGBMRegressor(**best_params_lgb)
model_lgb_optuna.fit(X_train, y_train)

[I 2026-02-16 23:53:37,406] A new study created in memory with name: no-name-9806acf6-f08f-4184-ad30-d078f0d89d84
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,504] Trial 0 finished with value: -0.21276154183246443 and parameters: {'num_leaves': 20, 'max_depth': 5, 'learning_rate': 0.28570714885887566, 'n_estimators': 247, 'min_child_samples': 20, 'subsample': 0.7468055921327309, 'colsample_bytree': 0.7467983561008608, 'reg_alpha': 0.2904180608409973, 'reg_lambda': 4.330880728874676}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,565] Trial 1 finished with value: -0.21947374132334996 and parameters: {'num_leaves': 20, 'max_depth': 7, 'learning_rate': 0.21534104756085318, 'n_estimators': 104, 'min_child_samples': 30, 'subsample': 0.9497327922401265, 'colsample_bytree': 0.7637017332034828, 'reg_alpha': 0.9091248360355031, 'reg_lambda': 0.9170225492671691}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,617] Trial 2 finished with value: -0.21570194906003645 and parameters: {'num_leaves': 20, 'max_depth': 5, 'learning_rate': 0.16217936517334897, 'n_estimators': 186, 'min_child_samples': 12, 'subsample': 0.8835558684167139, 'colsample_bytree': 0.7418481581956126, 'reg_alpha': 1.4607232426760908, 'reg_lambda': 1.8318092164684585}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,670] Trial 3 finished with value: -0.23261055689825724 and parameters: {'num_leaves': 20, 'max_depth': 6, 'learning_rate': 0.23770102880397392, 'n_estimators': 140, 'min_child_samples': 18, 'subsample': 0.8777243706586128, 'colsample_bytree': 0.7139351238159993, 'reg_alpha': 3.0377242595071916, 'reg_lambda': 0.8526206184364576}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,720] Trial 4 finished with value: -0.2403887046112042 and parameters: {'num_leaves': 20, 'max_depth': 3, 'learning_rate': 0.2851768058034666, 'n_estimators': 294, 'min_child_samples': 26, 'subsample': 0.7913841307520112, 'colsample_bytree': 0.7293016342019151, 'reg_alpha': 3.4211651325607844, 'reg_lambda': 2.2007624686980067}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,769] Trial 5 finished with value: -0.22739961465384706 and parameters: {'num_leaves': 20, 'max_depth': 3, 'learning_rate': 0.15360130393226834, 'n_estimators': 106, 'min_child_samples': 28, 'subsample': 0.777633994480005, 'colsample_bytree': 0.8987566853061946, 'reg_alpha': 1.5585553804470549, 'reg_lambda': 2.600340105889054}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,864] Trial 6 finished with value: -0.23151294737666417 and parameters: {'num_leaves': 20, 'max_depth': 7, 'learning_rate': 0.06360779210240283, 'n_estimators': 294, 'min_child_samples': 25, 'subsample': 0.9818496824692567, 'colsample_bytree': 0.9684482051282947, 'reg_alpha': 2.9894998940554256, 'reg_lambda': 4.609371175115584}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,915] Trial 7 finished with value: -0.242730111736252 and parameters: {'num_leaves': 20, 'max_depth': 3, 'learning_rate': 0.0668350301015521, 'n_estimators': 109, 'min_child_samples': 13, 'subsample': 0.8166031869068446, 'colsample_bytree': 0.7814047095321688, 'reg_alpha': 4.143687545759647, 'reg_lambda': 1.7837666334679465}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:37,962] Trial 8 finished with value: -0.2419939531707529 and parameters: {'num_leaves': 20, 'max_depth': 5, 'learning_rate': 0.16738186411589207, 'n_estimators': 128, 'min_child_samples': 25, 'subsample': 0.7223651931039312, 'colsample_bytree': 0.9960660809801551, 'reg_alpha': 3.861223846483287, 'reg_lambda': 0.993578407670862}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:38,009] Trial 9 finished with value: -0.22634409271089237 and parameters: {'num_leaves': 20, 'max_depth': 3, 'learning_rate': 0.2464838142519019, 'n_estimators': 242, 'min_child_samples': 23, 'subsample': 0.9313811040057838, 'colsample_bytree': 0.7222133955202271, 'reg_alpha': 1.7923286427213632, 'reg_lambda': 0.5793452976256486}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:38,197] Trial 10 finished with value: -0.23478672571066747 and parameters: {'num_leaves': 20, 'max_depth': 10, 'learning_rate': 0.011739183057187047, 'n_estimators': 232, 'min_child_samples': 5, 'subsample': 0.7046103211984313, 'colsample_bytree': 0.8314242782385489, 'reg_alpha': 0.0757211855137844, 'reg_lambda': 4.880699499289976}. Best is trial 0 with value: -0.21276154183246443.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:38,289] Trial 11 finished with value: -0.2107770410074176 and parameters: {'num_leaves': 20, 'max_depth': 5, 'learning_rate': 0.29696190488976976, 'n_estimators': 184, 'min_child_samples': 12, 'subsample': 0.8791642940492395, 'colsample_bytree': 0.8185202661129731, 'reg_alpha': 0.23304486130435842, 'reg_lambda': 3.4928387712913023}. Best is trial 11 with value: -0.2107770410074176.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:38,387] Trial 12 finished with value: -0.21171248579410237 and parameters: {'num_leaves': 20, 'max_depth': 5, 'learning_rate': 0.29970627227984975, 'n_estimators': 180, 'min_child_samples': 18, 'subsample': 0.8496639624800308, 'colsample_bytree': 0.8093326909715368, 'reg_alpha': 0.10512877265791049, 'reg_lambda': 3.574225304316241}. Best is trial 11 with value: -0.2107770410074176.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:38,441] Trial 13 finished with value: -0.2470718590545862 and parameters: {'num_leaves': 20, 'max_depth': 9, 'learning_rate': 0.2985394610188711, 'n_estimators': 171, 'min_child_samples': 13, 'subsample': 0.8427115618335728, 'colsample_bytree': 0.8369630069952888, 'reg_alpha': 4.996812193207756, 'reg_lambda': 3.485347699219401}. Best is trial 11 with value: -0.2107770410074176.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:38,533] Trial 14 finished with value: -0.21011035397924152 and parameters: {'num_leaves': 20, 'max_depth': 6, 'learning_rate': 0.20238786429747496, 'n_estimators': 162, 'min_child_samples': 8, 'subsample': 0.906092906282112, 'colsample_bytree': 0.8768075437408684, 'reg_alpha': 0.6940641877629383, 'reg_lambda': 3.5265189218808097}. Best is trial 14 with value: -0.21011035397924152.
C:\Users\jvend\AppData\Local\Temp\ipykernel_34596\848519506.py:7: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'num_leaves': trial.suggest_int('num_leaves', 20, 100, 150),
c:\Users\jvend\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\distributions.py:684: UserWarning: The distribution is specified by [20, 100] and step=150, but the range is not divisible by `step`. It will be replaced with [20, 20].
  optuna_warn(
[I 2026-02-16 23:53:38,618] Trial 15 finished with value: -0.21426759436704465 and parameters: {'num_leaves': 20, 'max_depth': 8, 'learning_rate': 0.19885610000226672, 'n_estimators': 212, 'min_child_samples': 7, 'subsample': 0.9114781247804531, 'colsample_bytree': 0.8977085814426922, 'reg_alpha': 0.9660956277259602, 'reg_lambda': 3.2926740600103415}. Best is trial 14 with value: -0.21011035397924152.

Mejores hiperparámetros LightGBM: {'num_leaves': 20, 'max_depth': 7, 'learning_rate': 0.07120409347777255, 'n_estimators': 255, 'min_child_samples': 11, 'subsample': 0.8891490606170778, 'colsample_bytree': 0.7583648488293474, 'reg_alpha': 0.07493016881369954, 'reg_lambda': 3.841235401211049}

LGBMRegressor(colsample_bytree=0.7583648488293474,
              learning_rate=0.07120409347777255, max_depth=7,
              min_child_samples=11, n_estimators=255, num_leaves=20,
              reg_alpha=0.07493016881369954, reg_lambda=3.841235401211049,
              subsample=0.8891490606170778)

In [119]:
y_test_pred = pd.read_csv("./data/test2.csv", sep=';')
y_test_pred.set_index("laptop_ID", inplace=True)    

#predecir(grid_search_rf, X_pred, y_test_pred)
# Evaluación en test
predecir(model_xgb_optuna, X_pred, y_test_pred)
predecir(model_lgb_optuna, X_pred, y_test_pred)

RMSE (log1p): 299.8463
299.8463148014329
723.3320331742951
RMSE (log1p): 318.1985
318.1984797903868
723.3320331742951

In [120]:
import optuna
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error

def objective_rf(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 600),
        'max_depth': trial.suggest_int('max_depth', 5, 40),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
        'random_state': 42
    }
    model = RandomForestRegressor(**params)
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error').mean()
    return score

study_rf = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study_rf.optimize(objective_rf, n_trials=50)

print("Mejores hiperparámetros RandomForest (Optuna):", study_rf.best_params)

best_params_rf = study_rf.best_params
model_rf_optuna = RandomForestRegressor(**best_params_rf)
model_rf_optuna.fit(X_train, y_train)

[I 2026-02-16 23:53:55,464] A new study created in memory with name: no-name-16df1d3a-6576-4546-91d3-194c1392db5c
[I 2026-02-16 23:53:56,099] Trial 0 finished with value: -0.2441116180504602 and parameters: {'n_estimators': 287, 'max_depth': 39, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: -0.2441116180504602.
[I 2026-02-16 23:53:56,804] Trial 1 finished with value: -0.2514732722657953 and parameters: {'n_estimators': 454, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: -0.2441116180504602.
[I 2026-02-16 23:53:58,223] Trial 2 finished with value: -0.2320440892672674 and parameters: {'n_estimators': 316, 'max_depth': 15, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True}. Best is trial 2 with value: -0.2320440892672674.
[I 2026-02-16 23:53:59,649] Trial 3 finished with value: -0.2453670061818538 and parameters: {'n_estimators': 357, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True}. Best is trial 2 with value: -0.2320440892672674.
[I 2026-02-16 23:54:00,147] Trial 4 finished with value: -0.24322228475604638 and parameters: {'n_estimators': 252, 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 2 with value: -0.2320440892672674.
[I 2026-02-16 23:54:01,018] Trial 5 finished with value: -0.24453519859988485 and parameters: {'n_estimators': 431, 'max_depth': 16, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 2 with value: -0.2320440892672674.
[I 2026-02-16 23:54:04,046] Trial 6 finished with value: -0.3014955129023353 and parameters: {'n_estimators': 399, 'max_depth': 38, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 2 with value: -0.2320440892672674.
[I 2026-02-16 23:54:05,296] Trial 7 finished with value: -0.2315174580606271 and parameters: {'n_estimators': 278, 'max_depth': 15, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True}. Best is trial 7 with value: -0.2315174580606271.
[I 2026-02-16 23:54:05,498] Trial 8 finished with value: -0.2397101726741232 and parameters: {'n_estimators': 102, 'max_depth': 34, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 7 with value: -0.2315174580606271.
[I 2026-02-16 23:54:06,346] Trial 9 finished with value: -0.23550201661909495 and parameters: {'n_estimators': 412, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 7 with value: -0.2315174580606271.
[I 2026-02-16 23:54:10,229] Trial 10 finished with value: -0.2797758070938982 and parameters: {'n_estimators': 573, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False}. Best is trial 7 with value: -0.2315174580606271.
[I 2026-02-16 23:54:11,166] Trial 11 finished with value: -0.23237276113842065 and parameters: {'n_estimators': 206, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': True}. Best is trial 7 with value: -0.2315174580606271.
[I 2026-02-16 23:54:11,979] Trial 12 finished with value: -0.22952686938947484 and parameters: {'n_estimators': 172, 'max_depth': 20, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 12 with value: -0.22952686938947484.
[I 2026-02-16 23:54:12,813] Trial 13 finished with value: -0.22632107357074618 and parameters: {'n_estimators': 158, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 13 with value: -0.22632107357074618.
[I 2026-02-16 23:54:13,412] Trial 14 finished with value: -0.22664717606749485 and parameters: {'n_estimators': 110, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 13 with value: -0.22632107357074618.
[I 2026-02-16 23:54:13,868] Trial 15 finished with value: -0.23250555060901534 and parameters: {'n_estimators': 100, 'max_depth': 31, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True}. Best is trial 13 with value: -0.22632107357074618.
[I 2026-02-16 23:54:14,496] Trial 16 finished with value: -0.2567611688395201 and parameters: {'n_estimators': 168, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}. Best is trial 13 with value: -0.22632107357074618.
[I 2026-02-16 23:54:15,230] Trial 17 finished with value: -0.22845561021087146 and parameters: {'n_estimators': 149, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': True}. Best is trial 13 with value: -0.22632107357074618.
[I 2026-02-16 23:54:15,796] Trial 18 finished with value: -0.21448850654042137 and parameters: {'n_estimators': 225, 'max_depth': 34, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:16,249] Trial 19 finished with value: -0.22543141668872577 and parameters: {'n_estimators': 220, 'max_depth': 34, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:16,729] Trial 20 finished with value: -0.22544505061970757 and parameters: {'n_estimators': 229, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:17,199] Trial 21 finished with value: -0.22942238642550117 and parameters: {'n_estimators': 235, 'max_depth': 34, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:17,646] Trial 22 finished with value: -0.22538843693105717 and parameters: {'n_estimators': 213, 'max_depth': 37, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:18,382] Trial 23 finished with value: -0.22114941014464837 and parameters: {'n_estimators': 345, 'max_depth': 37, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:19,145] Trial 24 finished with value: -0.22114699229345822 and parameters: {'n_estimators': 347, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:20,254] Trial 25 finished with value: -0.22106076659006435 and parameters: {'n_estimators': 509, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:21,468] Trial 26 finished with value: -0.2171217847664175 and parameters: {'n_estimators': 498, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:22,732] Trial 27 finished with value: -0.2170053772191675 and parameters: {'n_estimators': 521, 'max_depth': 40, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:23,996] Trial 28 finished with value: -0.21868971259300776 and parameters: {'n_estimators': 587, 'max_depth': 31, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:25,013] Trial 29 finished with value: -0.22598668369981426 and parameters: {'n_estimators': 528, 'max_depth': 37, 'min_samples_split': 18, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 18 with value: -0.21448850654042137.
[I 2026-02-16 23:54:26,303] Trial 30 finished with value: -0.2141274342538324 and parameters: {'n_estimators': 490, 'max_depth': 40, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 30 with value: -0.2141274342538324.
[I 2026-02-16 23:54:27,564] Trial 31 finished with value: -0.21409462457409711 and parameters: {'n_estimators': 488, 'max_depth': 40, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 31 with value: -0.21409462457409711.
[I 2026-02-16 23:54:28,813] Trial 32 finished with value: -0.21394784024173055 and parameters: {'n_estimators': 475, 'max_depth': 36, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 32 with value: -0.21394784024173055.
[I 2026-02-16 23:54:30,046] Trial 33 finished with value: -0.2138808052575342 and parameters: {'n_estimators': 469, 'max_depth': 36, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 33 with value: -0.2138808052575342.
[I 2026-02-16 23:54:31,288] Trial 34 finished with value: -0.21392672740273364 and parameters: {'n_estimators': 476, 'max_depth': 36, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 33 with value: -0.2138808052575342.
[I 2026-02-16 23:54:32,306] Trial 35 finished with value: -0.21616017133052493 and parameters: {'n_estimators': 464, 'max_depth': 28, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 33 with value: -0.2138808052575342.
[I 2026-02-16 23:54:33,086] Trial 36 finished with value: -0.23760034612115474 and parameters: {'n_estimators': 453, 'max_depth': 36, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False}. Best is trial 33 with value: -0.2138808052575342.
[I 2026-02-16 23:54:34,615] Trial 37 finished with value: -0.21345260918591177 and parameters: {'n_estimators': 552, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 37 with value: -0.21345260918591177.
[I 2026-02-16 23:54:35,945] Trial 38 finished with value: -0.21705707357728762 and parameters: {'n_estimators': 553, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 37 with value: -0.21345260918591177.
[I 2026-02-16 23:54:36,612] Trial 39 finished with value: -0.23639035310539483 and parameters: {'n_estimators': 393, 'max_depth': 26, 'min_samples_split': 19, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}. Best is trial 37 with value: -0.21345260918591177.
[I 2026-02-16 23:54:37,614] Trial 40 finished with value: -0.21772892084155968 and parameters: {'n_estimators': 436, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 37 with value: -0.21345260918591177.
[I 2026-02-16 23:54:39,062] Trial 41 finished with value: -0.21358446912533194 and parameters: {'n_estimators': 541, 'max_depth': 38, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 37 with value: -0.21345260918591177.
[I 2026-02-16 23:54:40,574] Trial 42 finished with value: -0.2134434668237907 and parameters: {'n_estimators': 542, 'max_depth': 38, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 42 with value: -0.2134434668237907.
[I 2026-02-16 23:54:41,890] Trial 43 finished with value: -0.2170961874064258 and parameters: {'n_estimators': 542, 'max_depth': 38, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 42 with value: -0.2134434668237907.
[I 2026-02-16 23:54:42,846] Trial 44 finished with value: -0.2414816633657121 and parameters: {'n_estimators': 600, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 42 with value: -0.2134434668237907.
[I 2026-02-16 23:54:43,862] Trial 45 finished with value: -0.22275155340789687 and parameters: {'n_estimators': 564, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False}. Best is trial 42 with value: -0.2134434668237907.
[I 2026-02-16 23:54:45,361] Trial 46 finished with value: -0.21343165683861062 and parameters: {'n_estimators': 544, 'max_depth': 38, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 46 with value: -0.21343165683861062.
[I 2026-02-16 23:54:46,531] Trial 47 finished with value: -0.22120450646031053 and parameters: {'n_estimators': 538, 'max_depth': 38, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 46 with value: -0.21343165683861062.
[I 2026-02-16 23:54:47,558] Trial 48 finished with value: -0.2391739105496289 and parameters: {'n_estimators': 572, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 46 with value: -0.21343165683861062.
[I 2026-02-16 23:54:48,520] Trial 49 finished with value: -0.22238396253030235 and parameters: {'n_estimators': 520, 'max_depth': 13, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 46 with value: -0.21343165683861062.

Mejores hiperparámetros RandomForest (Optuna): {'n_estimators': 544, 'max_depth': 38, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}

RandomForestRegressor(bootstrap=False, max_depth=38, max_features='sqrt',
                      min_samples_split=3, n_estimators=544)

In [121]:
predecir(model_rf_optuna, X_pred, y_test_pred)

RMSE (log1p): 319.8967
319.8966836476069
723.3320331742951

In [122]:
import optuna
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
import numpy as np

# Función objetivo para Optuna
def objective(trial):

    params = {
        "iterations": trial.suggest_int("iterations", 800, 2500),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.05),
        "depth": trial.suggest_int("depth", 4, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1, 10),
        "random_strength": trial.suggest_float("random_strength", 0.5, 2.0),
        "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 1.0),
        "border_count": trial.suggest_int("border_count", 64, 254),
        "loss_function": "RMSE",
        "eval_metric": "RMSE",
        "verbose": False,
        "random_seed": 42
    }

    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    rmses = []

    for train_idx, valid_idx in kf.split(X_train):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[valid_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[valid_idx]

        model = CatBoostRegressor(**params)
        model.fit(X_tr, y_tr)

        # Predicción en log
        y_pred_log = model.predict(X_val)
        y_pred = np.expm1(y_pred_log)
        y_val = np.expm1(y_val)


        # RMSE real
        rmse = np.sqrt(mean_squared_error(y_val, y_pred))
        rmses.append(rmse)

    return np.mean(rmses)

# Ejecutar Optuna
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=60)

print("Mejores parámetros:", study.best_params)
print("Mejor RMSE:", study.best_value)

[I 2026-02-16 23:54:56,549] A new study created in memory with name: no-name-5a8cef14-c975-4734-9966-0a629e7a94ac
[I 2026-02-16 23:54:59,795] Trial 0 finished with value: 284.2844802131211 and parameters: {'iterations': 1370, 'learning_rate': 0.014168492380332874, 'depth': 4, 'l2_leaf_reg': 4.875518504369687, 'random_strength': 1.5207695888103334, 'bagging_temperature': 0.2979818924340496, 'border_count': 111}. Best is trial 0 with value: 284.2844802131211.
[I 2026-02-16 23:55:05,663] Trial 1 finished with value: 277.5631300061019 and parameters: {'iterations': 1338, 'learning_rate': 0.04741141696005516, 'depth': 5, 'l2_leaf_reg': 9.019192653136676, 'random_strength': 1.2012871373940865, 'bagging_temperature': 0.18839182022543677, 'border_count': 250}. Best is trial 1 with value: 277.5631300061019.
[I 2026-02-16 23:55:09,213] Trial 2 finished with value: 287.1341544433808 and parameters: {'iterations': 859, 'learning_rate': 0.03463369977252167, 'depth': 5, 'l2_leaf_reg': 9.257329122502327, 'random_strength': 0.5730029543826948, 'bagging_temperature': 0.22664418433420475, 'border_count': 230}. Best is trial 1 with value: 277.5631300061019.
[I 2026-02-16 23:55:29,227] Trial 3 finished with value: 295.8455099511174 and parameters: {'iterations': 2393, 'learning_rate': 0.03646824587456096, 'depth': 8, 'l2_leaf_reg': 1.1989095447401894, 'random_strength': 0.880791435438565, 'bagging_temperature': 0.12025876318652173, 'border_count': 84}. Best is trial 1 with value: 277.5631300061019.
[I 2026-02-16 23:55:34,927] Trial 4 finished with value: 283.9514492850123 and parameters: {'iterations': 1313, 'learning_rate': 0.04399776873992584, 'depth': 6, 'l2_leaf_reg': 9.832612924509089, 'random_strength': 0.6263214518127769, 'bagging_temperature': 0.6406170149165796, 'border_count': 85}. Best is trial 1 with value: 277.5631300061019.
[I 2026-02-16 23:56:31,426] Trial 5 finished with value: 316.0906933191468 and parameters: {'iterations': 1302, 'learning_rate': 0.03746146669680926, 'depth': 10, 'l2_leaf_reg': 6.768474129429466, 'random_strength': 0.6471571343209225, 'bagging_temperature': 0.014795264088748983, 'border_count': 239}. Best is trial 1 with value: 277.5631300061019.
[I 2026-02-16 23:56:37,128] Trial 6 finished with value: 269.38563197435644 and parameters: {'iterations': 2100, 'learning_rate': 0.03848492930995798, 'depth': 4, 'l2_leaf_reg': 5.893537390964118, 'random_strength': 1.5107651156869095, 'bagging_temperature': 0.9288157824419516, 'border_count': 75}. Best is trial 6 with value: 269.38563197435644.
[I 2026-02-16 23:56:42,991] Trial 7 finished with value: 272.79445000842395 and parameters: {'iterations': 1664, 'learning_rate': 0.04292081237919982, 'depth': 4, 'l2_leaf_reg': 9.314799926436242, 'random_strength': 1.5283558471802157, 'bagging_temperature': 0.3552618715564859, 'border_count': 180}. Best is trial 6 with value: 269.38563197435644.
[I 2026-02-16 23:56:48,308] Trial 8 finished with value: 267.85132633212754 and parameters: {'iterations': 1311, 'learning_rate': 0.02908302953540541, 'depth': 4, 'l2_leaf_reg': 3.2151490718376396, 'random_strength': 1.945396091715697, 'bagging_temperature': 0.6504214060469509, 'border_count': 232}. Best is trial 8 with value: 267.85132633212754.
[I 2026-02-16 23:56:57,941] Trial 9 finished with value: 299.86932353636473 and parameters: {'iterations': 865, 'learning_rate': 0.02490971785089178, 'depth': 8, 'l2_leaf_reg': 5.476307665796921, 'random_strength': 1.471978516867381, 'bagging_temperature': 0.48209276813729174, 'border_count': 139}. Best is trial 8 with value: 267.85132633212754.
[I 2026-02-16 23:57:15,473] Trial 10 finished with value: 290.85596721900527 and parameters: {'iterations': 1852, 'learning_rate': 0.024845861915960735, 'depth': 7, 'l2_leaf_reg': 2.199771475282221, 'random_strength': 1.926863832897265, 'bagging_temperature': 0.7624686717526703, 'border_count': 190}. Best is trial 8 with value: 267.85132633212754.
[I 2026-02-16 23:57:21,665] Trial 11 finished with value: 267.61985668171263 and parameters: {'iterations': 2080, 'learning_rate': 0.02813861714277656, 'depth': 4, 'l2_leaf_reg': 3.532712031054908, 'random_strength': 1.9522225568787972, 'bagging_temperature': 0.9686270420815117, 'border_count': 143}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:57:35,056] Trial 12 finished with value: 275.6575965813197 and parameters: {'iterations': 2106, 'learning_rate': 0.027007400186304695, 'depth': 6, 'l2_leaf_reg': 3.3652324578624073, 'random_strength': 1.9991107289732666, 'bagging_temperature': 0.9205240281220162, 'border_count': 151}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:57:47,906] Trial 13 finished with value: 272.3690463089718 and parameters: {'iterations': 2500, 'learning_rate': 0.017448315201554286, 'depth': 5, 'l2_leaf_reg': 3.3099193626317676, 'random_strength': 1.7600281409724676, 'bagging_temperature': 0.7304650575627951, 'border_count': 196}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:58:58,653] Trial 14 finished with value: 311.9263781080325 and parameters: {'iterations': 1911, 'learning_rate': 0.019430061408365153, 'depth': 10, 'l2_leaf_reg': 3.738177531639799, 'random_strength': 1.767834968861703, 'bagging_temperature': 0.5486030926516399, 'border_count': 119}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:59:06,636] Trial 15 finished with value: 281.93970438859554 and parameters: {'iterations': 1102, 'learning_rate': 0.030793809599791253, 'depth': 6, 'l2_leaf_reg': 1.887490469822746, 'random_strength': 1.1867763081817482, 'bagging_temperature': 0.8244787964776681, 'border_count': 210}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:59:12,053] Trial 16 finished with value: 272.4080729003836 and parameters: {'iterations': 1587, 'learning_rate': 0.030375765051817497, 'depth': 4, 'l2_leaf_reg': 4.254727656209512, 'random_strength': 1.813934922526846, 'bagging_temperature': 0.9920296347980853, 'border_count': 164}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:59:23,420] Trial 17 finished with value: 286.2456379040053 and parameters: {'iterations': 2246, 'learning_rate': 0.010054276587204203, 'depth': 5, 'l2_leaf_reg': 7.077659739930299, 'random_strength': 1.675073681004353, 'bagging_temperature': 0.4629886703896855, 'border_count': 214}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:59:34,402] Trial 18 finished with value: 287.753951554327 and parameters: {'iterations': 1647, 'learning_rate': 0.021670655196502624, 'depth': 7, 'l2_leaf_reg': 2.695938841668672, 'random_strength': 1.0436522860299662, 'bagging_temperature': 0.6334082607965034, 'border_count': 127}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-16 23:59:58,185] Trial 19 finished with value: 298.21088946183806 and parameters: {'iterations': 1078, 'learning_rate': 0.03242885881045313, 'depth': 9, 'l2_leaf_reg': 1.1368649921413851, 'random_strength': 1.8887294668932209, 'bagging_temperature': 0.822234825385966, 'border_count': 169}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:00:09,701] Trial 20 finished with value: 288.276490470346 and parameters: {'iterations': 1905, 'learning_rate': 0.026904358163187387, 'depth': 7, 'l2_leaf_reg': 4.746192974843001, 'random_strength': 1.3713839363506635, 'bagging_temperature': 0.6470689832676552, 'border_count': 101}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:00:15,302] Trial 21 finished with value: 271.46581873456523 and parameters: {'iterations': 2118, 'learning_rate': 0.0395048325330767, 'depth': 4, 'l2_leaf_reg': 6.864372973021043, 'random_strength': 1.6460030460332729, 'bagging_temperature': 0.9786762438157421, 'border_count': 70}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:00:21,901] Trial 22 finished with value: 268.540698337894 and parameters: {'iterations': 2101, 'learning_rate': 0.033444066207592195, 'depth': 4, 'l2_leaf_reg': 5.925222756535755, 'random_strength': 1.6293115131165956, 'bagging_temperature': 0.8863777707505177, 'border_count': 147}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:00:30,049] Trial 23 finished with value: 277.93916891624457 and parameters: {'iterations': 1738, 'learning_rate': 0.03318308037331667, 'depth': 5, 'l2_leaf_reg': 8.118962637998983, 'random_strength': 1.9872551061285397, 'bagging_temperature': 0.8742065549544056, 'border_count': 145}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:00:36,634] Trial 24 finished with value: 270.50328639861146 and parameters: {'iterations': 2305, 'learning_rate': 0.022360519947776252, 'depth': 4, 'l2_leaf_reg': 6.0116311309281825, 'random_strength': 1.6697528364532042, 'bagging_temperature': 0.7112820893057723, 'border_count': 134}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:00:43,767] Trial 25 finished with value: 276.8433138894841 and parameters: {'iterations': 1477, 'learning_rate': 0.02817093368999569, 'depth': 5, 'l2_leaf_reg': 4.2208456226801605, 'random_strength': 1.8578141689629577, 'bagging_temperature': 0.8573552758466869, 'border_count': 161}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:00:57,152] Trial 26 finished with value: 276.43046712537034 and parameters: {'iterations': 2042, 'learning_rate': 0.029243421698798667, 'depth': 6, 'l2_leaf_reg': 2.7695769790457385, 'random_strength': 1.3727802778673301, 'bagging_temperature': 0.5520222151429718, 'border_count': 178}. Best is trial 11 with value: 267.61985668171263.
[I 2026-02-17 00:01:00,302] Trial 27 finished with value: 267.42278668755114 and parameters: {'iterations': 1076, 'learning_rate': 0.041074221796601945, 'depth': 4, 'l2_leaf_reg': 5.004939083954664, 'random_strength': 1.6521469510219924, 'bagging_temperature': 0.7607493841255022, 'border_count': 107}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:04,322] Trial 28 finished with value: 273.15712122626894 and parameters: {'iterations': 1134, 'learning_rate': 0.04891126386194958, 'depth': 5, 'l2_leaf_reg': 5.056009667166438, 'random_strength': 1.7735692301926926, 'bagging_temperature': 0.7716781513165101, 'border_count': 102}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:07,016] Trial 29 finished with value: 269.3370977247685 and parameters: {'iterations': 992, 'learning_rate': 0.04183688958201421, 'depth': 4, 'l2_leaf_reg': 4.225314544438675, 'random_strength': 1.9172228113139291, 'bagging_temperature': 0.4333220637592376, 'border_count': 108}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:11,005] Trial 30 finished with value: 280.9368332658725 and parameters: {'iterations': 1463, 'learning_rate': 0.01545470290505947, 'depth': 4, 'l2_leaf_reg': 4.919065763553007, 'random_strength': 1.5679494871049113, 'bagging_temperature': 0.6891425171008867, 'border_count': 117}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:15,066] Trial 31 finished with value: 272.5380908937447 and parameters: {'iterations': 1252, 'learning_rate': 0.03434732200521051, 'depth': 4, 'l2_leaf_reg': 6.020689154336112, 'random_strength': 1.3835244794983703, 'bagging_temperature': 0.9249029495223047, 'border_count': 152}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:18,332] Trial 32 finished with value: 267.9817729581955 and parameters: {'iterations': 1201, 'learning_rate': 0.04524565743052747, 'depth': 4, 'l2_leaf_reg': 3.7973958647635246, 'random_strength': 1.6424994330602434, 'bagging_temperature': 0.7867289261221182, 'border_count': 127}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:22,527] Trial 33 finished with value: 274.84202131154996 and parameters: {'iterations': 1196, 'learning_rate': 0.04753029672274028, 'depth': 5, 'l2_leaf_reg': 3.5913683482052194, 'random_strength': 1.7259089501638136, 'bagging_temperature': 0.7981636818736317, 'border_count': 132}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:25,658] Trial 34 finished with value: 274.34507072640423 and parameters: {'iterations': 976, 'learning_rate': 0.04111627654409959, 'depth': 5, 'l2_leaf_reg': 2.8349884863245682, 'random_strength': 1.848301641049341, 'bagging_temperature': 0.5827579367676236, 'border_count': 89}. Best is trial 27 with value: 267.42278668755114.
[I 2026-02-17 00:01:29,482] Trial 35 finished with value: 265.0385657826808 and parameters: {'iterations': 1411, 'learning_rate': 0.044732858479025174, 'depth': 4, 'l2_leaf_reg': 4.005294232053438, 'random_strength': 1.2857311452761668, 'bagging_temperature': 0.6863687004557725, 'border_count': 125}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:01:38,884] Trial 36 finished with value: 276.3903119219068 and parameters: {'iterations': 1419, 'learning_rate': 0.03676358780301583, 'depth': 6, 'l2_leaf_reg': 1.952382231571654, 'random_strength': 1.0621245829803758, 'bagging_temperature': 0.6076016879515721, 'border_count': 252}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:01:43,585] Trial 37 finished with value: 276.9750971838286 and parameters: {'iterations': 1359, 'learning_rate': 0.04596561749818217, 'depth': 5, 'l2_leaf_reg': 4.615937588013702, 'random_strength': 0.8422798196824322, 'bagging_temperature': 0.6671624501476374, 'border_count': 92}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:01:48,129] Trial 38 finished with value: 266.600827515026 and parameters: {'iterations': 1554, 'learning_rate': 0.04989936706338918, 'depth': 4, 'l2_leaf_reg': 3.072103243905824, 'random_strength': 1.2965922696788015, 'bagging_temperature': 0.41271131762635827, 'border_count': 118}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:01:52,331] Trial 39 finished with value: 269.57799005447896 and parameters: {'iterations': 1537, 'learning_rate': 0.04397891709772983, 'depth': 4, 'l2_leaf_reg': 5.45571231956947, 'random_strength': 1.1709342683444026, 'bagging_temperature': 0.2949370807282697, 'border_count': 117}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:07,614] Trial 40 finished with value: 297.77437617589004 and parameters: {'iterations': 1766, 'learning_rate': 0.049800171154160036, 'depth': 8, 'l2_leaf_reg': 2.431209699381178, 'random_strength': 1.2846167046009933, 'bagging_temperature': 0.38127694926278516, 'border_count': 101}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:12,182] Trial 41 finished with value: 266.8232479081096 and parameters: {'iterations': 1356, 'learning_rate': 0.04014148966860577, 'depth': 4, 'l2_leaf_reg': 3.1458712485341005, 'random_strength': 1.4469917103818357, 'bagging_temperature': 0.5191219686223292, 'border_count': 228}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:14,698] Trial 42 finished with value: 266.67797563217664 and parameters: {'iterations': 800, 'learning_rate': 0.040457804690916296, 'depth': 4, 'l2_leaf_reg': 1.4806247194716748, 'random_strength': 1.4741792092573927, 'bagging_temperature': 0.23066167877286203, 'border_count': 111}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:17,347] Trial 43 finished with value: 269.6935446442581 and parameters: {'iterations': 864, 'learning_rate': 0.03991340854911115, 'depth': 4, 'l2_leaf_reg': 1.8069018504323144, 'random_strength': 1.4361965369876306, 'bagging_temperature': 0.1813643026084718, 'border_count': 79}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:21,031] Trial 44 finished with value: 267.62845983017417 and parameters: {'iterations': 971, 'learning_rate': 0.04723453499061719, 'depth': 5, 'l2_leaf_reg': 1.423007897935459, 'random_strength': 1.2771941600171979, 'bagging_temperature': 0.06701598962826238, 'border_count': 110}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:23,330] Trial 45 finished with value: 271.3369826649978 and parameters: {'iterations': 803, 'learning_rate': 0.04386492446882516, 'depth': 4, 'l2_leaf_reg': 3.10216416510484, 'random_strength': 1.5634235825073, 'bagging_temperature': 0.2587900150006829, 'border_count': 91}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:41,829] Trial 46 finished with value: 303.9215932435841 and parameters: {'iterations': 1375, 'learning_rate': 0.03820974245853962, 'depth': 9, 'l2_leaf_reg': 1.5133002485146059, 'random_strength': 1.1078847666905025, 'bagging_temperature': 0.3621434543145622, 'border_count': 65}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:46,464] Trial 47 finished with value: 275.1541333964391 and parameters: {'iterations': 1034, 'learning_rate': 0.042160073481839984, 'depth': 5, 'l2_leaf_reg': 4.045597544917026, 'random_strength': 1.4487045668187806, 'bagging_temperature': 0.40583523453688153, 'border_count': 124}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:51,646] Trial 48 finished with value: 269.7290885372935 and parameters: {'iterations': 1553, 'learning_rate': 0.035419239021509424, 'depth': 4, 'l2_leaf_reg': 2.1928564978308236, 'random_strength': 1.3320812041655599, 'bagging_temperature': 0.14351865846276457, 'border_count': 97}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:02:58,316] Trial 49 finished with value: 283.88378945762935 and parameters: {'iterations': 1263, 'learning_rate': 0.04576146348589387, 'depth': 6, 'l2_leaf_reg': 3.0915570549770477, 'random_strength': 1.4967856989908668, 'bagging_temperature': 0.5240822168095165, 'border_count': 80}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:03:04,045] Trial 50 finished with value: 265.83384933587683 and parameters: {'iterations': 1632, 'learning_rate': 0.040225355580759674, 'depth': 4, 'l2_leaf_reg': 2.5081948707928445, 'random_strength': 1.235555805490239, 'bagging_temperature': 0.3206247931998844, 'border_count': 225}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:03:08,995] Trial 51 finished with value: 267.44551215173993 and parameters: {'iterations': 1643, 'learning_rate': 0.039980187216094344, 'depth': 4, 'l2_leaf_reg': 2.3668175301520367, 'random_strength': 0.9713979746912124, 'bagging_temperature': 0.3128004580476738, 'border_count': 233}. Best is trial 35 with value: 265.0385657826808.
[I 2026-02-17 00:03:14,845] Trial 52 finished with value: 263.7102329576563 and parameters: {'iterations': 1779, 'learning_rate': 0.04812792333254753, 'depth': 4, 'l2_leaf_reg': 2.4747459180710294, 'random_strength': 1.217958144829818, 'bagging_temperature': 0.2378076041478115, 'border_count': 242}. Best is trial 52 with value: 263.7102329576563.
[I 2026-02-17 00:03:21,245] Trial 53 finished with value: 259.59282790533615 and parameters: {'iterations': 1830, 'learning_rate': 0.047278441070127526, 'depth': 4, 'l2_leaf_reg': 1.6385531450693023, 'random_strength': 1.2262542342003215, 'bagging_temperature': 0.32343967319083694, 'border_count': 243}. Best is trial 53 with value: 259.59282790533615.
[I 2026-02-17 00:03:27,461] Trial 54 finished with value: 258.8903479396476 and parameters: {'iterations': 1781, 'learning_rate': 0.048143364090063284, 'depth': 4, 'l2_leaf_reg': 1.4392964169574116, 'random_strength': 1.2182814833610052, 'bagging_temperature': 0.22284739590632852, 'border_count': 241}. Best is trial 54 with value: 258.8903479396476.
[I 2026-02-17 00:03:36,047] Trial 55 finished with value: 265.5159185652693 and parameters: {'iterations': 1825, 'learning_rate': 0.047898566239183295, 'depth': 5, 'l2_leaf_reg': 1.1180885089525356, 'random_strength': 1.2184936301674254, 'bagging_temperature': 0.31180410378081735, 'border_count': 244}. Best is trial 54 with value: 258.8903479396476.

Mejores parámetros: {'iterations': 1781, 'learning_rate': 0.048143364090063284, 'depth': 4, 'l2_leaf_reg': 1.4392964169574116, 'random_strength': 1.2182814833610052, 'bagging_temperature': 0.22284739590632852, 'border_count': 241}
Mejor RMSE: 258.8903479396476

In [123]:
best_params = study.best_params 
best_params["loss_function"] = "RMSE" 
best_params["eval_metric"] = "RMSE" 
best_params["verbose"] = False 
best_params["random_seed"] = 42 
model = CatBoostRegressor(**best_params) 
# Entrenar en todo el dataset 
model.fit(X_train, y_train)
predecir(model, X_pred, y_test_pred)

RMSE (log1p): 291.8891
291.88911094526196
723.3320331742951

In [130]:
y_pred = model.predict(X_pred)
y_pred = np.expm1(y_pred)

rmse_log = np.sqrt(mean_squared_error(y_test_pred, y_pred))
print(f"RMSE (log1p): {rmse_log:.4f}")

submission = pd.DataFrame(y_pred, columns=["Price_in_euros"], index=X_pred.index)
submission = submission.reset_index()

RMSE (log1p): 291.8891

In [127]:
def chequeador(df_to_submit):
    """
    Esta función se asegura de que tu submission tenga la forma requerida por Kaggle.

    Si es así, se guardará el dataframe en un `csv` y estará listo para subir a Kaggle.

    Si no, LEE EL MENSAJE Y HAZLE CASO.

    Si aún no:
    - apaga tu ordenador,
    - date una vuelta,
    - enciendelo otra vez,
    - abre este notebook y
    - leelo todo de nuevo.
    Todos nos merecemos una segunda oportunidad. También tú.
    """
    if df_to_submit.shape == sample.shape:
        if df_to_submit.columns.all() == sample.columns.all():
            if df_to_submit.laptop_ID.all() == sample.laptop_ID.all():
                print("You're ready to submit!")
                df_to_submit.to_csv("submission.csv", index = False) #muy importante el index = False
                urllib.request.urlretrieve("https://www.mihaileric.com/static/evaluation-meme-e0a350f278a36346e6d46b139b1d0da0-ed51e.jpg", "gfg.png")
                img = Image.open("gfg.png")
                img.show()
            else:
                print("Check the ids and try again")
        else:
            print("Check the names of the columns and try again")
    else:
        print("Check the number of rows and/or columns and try again")
        print("\nMensaje secreto del TA: No me puedo creer que después de todo este notebook hayas hecho algún cambio en las filas de `test.csv`. Lloro.")

In [129]:
sample = pd.read_csv("data/sample_submission.csv")
chequeador(submission)

You're ready to submit!

In [124]:
# Ensemble: promedio de XGBoost, RandomForest y LightGBM (Optuna)
# Asegúrate de tener entrenados: model_xgb_optuna, model_rf_optuna, model_lgb_optuna

pred_xgb = model_xgb_optuna.predict(X_pred)
pred_rf = model_rf_optuna.predict(X_pred)
pred_lgb = model_lgb_optuna.predict(X_pred)
pred_cat = model.predict(X_pred)


ensemble_pred_3 = ( pred_xgb + pred_rf + pred_lgb + pred_cat ) / 4
ensemble_pred_3 = np.expm1(ensemble_pred_3)
#ensemble_pred_3 = ( pred_xgb + pred_rf ) / 2

# y_test_exp = np.expm1(y_test_pred)
# y_pred_exp = np.expm1(ensemble_pred_3)
rmse_original = np.sqrt(mean_squared_error(y_test_pred, ensemble_pred_3))
print(f"RMSE Ensemble (4 modelos): {rmse_original:.2f}")

RMSE Ensemble (4 modelos): 300.43

In [73]:
X_train.head()

,Company,TypeName,OpSys,Touchscreen,IPS,ResX,ResY,PPI,Cpu_brand,Cpu_family,...,Total_Storage,Ram_GB,Weight_kg,Cpu_gen,Gpu_model_num,Has_SSD,Has_HDD,ResCategory,Weight_norm,Ram_norm
laptop_ID,,,,,,,,,,,,,,,,,,,,,
1118,6.841171,7.097950,7.091761,0,1,1920.0,1080.0,127.335675,6.855549,7.263482,...,1000.0,8,3.00,67.0,6150.0,0,1,6.996008,0.638298,0.250
153,6.899758,7.369785,6.886584,0,0,1920.0,1080.0,141.211998,6.855549,7.263482,...,512.0,16,2.56,77.0,1050.0,1,0,6.996008,0.544681,0.500
275,6.961628,7.282348,6.936435,0,1,2560.0,1600.0,226.983005,6.855549,6.864683,...,512.0,8,1.37,NaN,550.0,1,0,7.341643,0.291489,0.250
1100,6.841171,6.516254,7.091761,0,0,1920.0,1080.0,157.350512,6.855549,6.864683,...,500.0,4,1.54,62.0,520.0,0,1,6.996008,0.327660,0.125
131,6.899758,6.516254,6.886584,0,0,1920.0,1080.0,127.335675,6.855549,7.263482,...,2256.0,16,2.80,85.0,530.0,1,1,6.996008,0.595745,0.500

In [32]:
# graba xtrain, y_train, xtest, ytest, xpred en csv para usarlo luego
X_train.to_csv("./data/X_train_processed.csv", index=True)
y_train.to_csv("./data/y_train.csv", index=True)
X_test.to_csv("./data/X_test_processed.csv", index=True)
y_test.to_csv("./data/y_test.csv", index=True)
X_pred.to_csv("./data/X_pred_processed.csv", index=True)

In [33]:
ensemble_pred_3 = pd.Series(ensemble_pred_3, index=X_pred.index)
ensemble_pred_3.to_csv("./data/ensemble_pred_3.csv", index=True)

PermissionError: [Errno 13] Permission denied: './data/ensemble_pred_3.csv'

In [34]:
y_train.describe()

count    729.000000
mean       6.826302
std        0.620752
min        5.262172
25%        6.395262
50%        6.893656
75%        7.286876
max        8.716044
Name: Price_in_euros, dtype: float64

In [35]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)
rmses = []

for train_idx, valid_idx in kf.split(X_train):
    X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[valid_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[valid_idx]

    y_tr_log = np.log1p(y_tr)

    model = LGBMRegressor(
        n_estimators=800,
        learning_rate=0.03,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    )

    model.fit(X_tr, y_tr_log)

    y_pred_log = model.predict(X_val)
    y_pred = np.expm1(y_pred_log)

    rmse = np.sqrt(mean_squared_error(y_val, y_pred))
    rmses.append(rmse)

print("RMSE promedio:", np.mean(rmses))

RMSE promedio: 0.19763443428611283